title: Antepassados
author: Flávio Dutra
email: flavio.adore@gmail.com
description: Sítio dedicado à genealogia, minhas descobertas e histórias familiares.
lang: pt-br
# baseurl: "" # the subpath of your site, e.g. /blog
url: https://antepassados.flaviodutra.com.br
logo: /assets/images/logo-mustard.png
keywords:
    - genealogia
    - história
    - migração
    - Europa
    - América do Sul
    - Brasil
    - Itália
    - Portugal
    - Açores
    - França

# Social
facebook:
    username: flaviodutra

github:
    username: flaviodut

social:
    links:
        - https://www.facebook.com/flaviodutra


# Build settings
permalink: /:year-:month-:day/:title
# markdown: kramdown
theme: minima
plugins:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-sitemap
include:
    - _redirects

# Configuration for Disqus
disqus:
    shortname: antepassados

# GA4
google_analytics: G-TPQY628EYT

# Compress HTML - http://jch.penibelst.de/
compress_html:
    clippings: all
    comments: all
    endings: []
    startings: []
    profile: false

# https://kylewbanks.com/blog/creating-category-pages-in-jekyll-without-plugins
collections:
    category:
        output: true

defaults:
    - scope:
          path: ''
          type: category
      values:
          layout: 'category'
