title: Antepassados
author: Flávio Alberto Dutra
email: flavio.adore@gmail.com
description: Sítio dedicado as minhas descobertas genealógicas e histórias familiares.
lang: pt-br
url: "http://antepassados.flaviodutra.com.br"

# Social
facebook_username: flaviodutra
twitter_username: flaviodut
github_username: flaviodut

# Build settings
permalink: /:year-:month-:day/:title
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
include:
  - _redirects

# Configuration for Disqus
disqus:
  shortname: antepassados

# GA
google_analytics: UA-35055763-2

# Compress HTML - http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: all
  endings: []
  startings: []
  profile: false

# https://kylewbanks.com/blog/creating-category-pages-in-jekyll-without-plugins
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"