# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Antepassados
author: Flávio Alberto Dutra
email: flavio.adore@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sítio dedicado as minhas descobertas genealógicas e histórias familiares.
lang: pt-br
baseurl: "/antepassados" # the subpath of your site, e.g. /blog
url: "http://flaviodutra.com.br" # the base hostname & protocol for your site, e.g. http://example.com

facebook_username: flaviodutra
twitter_username: flaviodut
github_username: flaviodut

# Build settings
permalink: /:year-:month-:day/:title
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Configuration for Disqus
disqus:
  shortname: antepassados

# GA
google_analytics: UA-35055763-2


# https://kylewbanks.com/blog/creating-category-pages-in-jekyll-without-plugins
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"